spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/handover #내부의 DB명으로 해야함! 코끼리이름X
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect